flags: {}
packages:
- '.'

extra-deps:
- sitepipe-0.4.0.2
- strptime-1.0.10
- MissingH-1.6.0.1

resolver: lts-18.16
nix:
  path: [nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-24.05.tar.gz]
  packages:
    - haskell.compiler.ghc810
    - pkg-config
    - zlib
    - unzip

